# Letter patterns for emoji art
# Each letter is stored as a list of rows, where each row is a string of emojis
# This allows building words row by row
}
LETTER_PATTERNS = {
    'a': {
        "line_1":["l4", "hl", "i2", "h1"],
        "line_2":["vl", "l4", "l3", "vl"],
        "line_3":["vl", "l1", "l2", "vl"],
        "line_4":["vl", "l4", "l3", "vl"],
        "line_5":["vl", "vl", "vl", "vl"],
        "line_6":["l1", "l2", "l1", "l2"],
    },
    'b': [
        'l4', 'hl', 'l3', 'gd',
        'vl', 'l4', 'x1', 'l3',
        'vl', 'l1', 'x1', 'l2',
        'vl', 'l4', 'x1', 'l3',
        'i1', 'l1', 'l2', 'vl',
        'h2', 'hl', 'hl', 'l2',
    ],
    'c': [
        'l4', 'h4', 'i4', 'l3',
        'vl', 'l4', 'l3', 'vl',
        'vl', 'vl', 'l1', 'l2',
        'vl', 'vl', 'l4', 'l3',
        'vl', 'l1', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    'd': [
        'l4', 'hl', 'l3', 'gd',
        'vl', 'l4', 'x1', 'l3',
        'vl', 'vl', 'vl', 'vl',
        'vl', 'vl', 'vl', 'i1',
        'vl', 'l1', 'l2', 'h1',
        'l1', 'hl', 'hl', 'l2',
    ],
    'e': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'hl', 'l2',
        'vl', 'l1', 'l3', 'gd',
        'vl', 'l4', 'l2', 'gd',
        'vl', 'l1', 'hl', 'l3',
        'l1', 'h4', 'i4', 'l2',
    ],
    'f': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'hl', 'l2',
        'vl', 'l1', 'l3', 'gd',
        'i1', 'l4', 'l2', 'gd',
        'h1', 'vl', 'gd', 'gd',
        'l1', 'l2', 'gd', 'gd',
    ],
    'g': [
        'l4', 'i2', 'h2', 'l3',
        'vl', 'l4', 'hl', 'l2',
        'vl', 't2', 'hl', 'l3',
        'vl', 't2', 'l3', 'vl',
        'vl', 'l1', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    'h': [
        'l4', 'l3', 'l4', 'l3',
        'vl', 'vl', 'vl', 'vl',
        'vl', 'l1', 'l2', 'i1',
        'vl', 'l4', 'l3', 'h1',
        'vl', 'vl', 'vl', 'vl',
        'l1', 'l2', 'l1', 'l2',
    ],
    'i': [
        'l4', 'hl', 'hl', 'l3',
        'l1', 'l3', 'l4', 'l2',
        'gd', 'vl', 'vl', 'gd',
        'gd', 'vl', 'vl', 'gd',
        'l4', 'l2', 'l1', 'l3',
        'l1', 'i2', 'h2', 'l2',
    ],
    'j': [
        'gd', 'l4', 'hl', 'l3',
        'gd', 'l1', 'l3', 'vl',
        'gd', 'gd', 'vl', 'i1',
        'l4', 'l3', 'vl', 'h1',
        'vl', 'l1', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    'k': [
        'l4', 'l3', 'l4', 'l3',
        'vl', 'l1', 'l2', 'vl',
        'i1', 'gd', 'l4', 'l2',
        'h1', 'gd', 'l1', 'l3',
        'vl', 'l4', 'l3', 'vl',
        'l1', 'l2', 'l1', 'l2',
    ],
    'l': [
        'l4', 'l3', 'gd', 'gd',
        'vl', 'vl', 'gd', 'gd',
        'vl', 'vl', 'gd', 'gd',
        'vl', 'vl', 'gd', 'gd',
        'vl', 'l1', 'hl', 'l3',
        'l1', 'h4', 'i4', 'l2',
    ],
    'm': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'gd', 'gd', 'vl',
        'vl', 'gd', 'gd', 'vl',
        'vl', 'i3', 'h1', 'vl',
        'vl', 'vl', 'vl', 'vl',
        'l1', 't3', 't3', 'l2',
    ],
    'n': [
        'l4', 'l3', 'l4', 'l3',
        'vl', 'l1', 't4', 'vl',
        'vl', 'gd', 'i1', 'vl',
        'vl', 'h1', 'gd', 'vl',
        'vl', 't2', 'l3', 'vl',
        'l1', 'l2', 'l1', 'l2',
    ],
    'o': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'l3', 'i1',
        'vl', 'i1', 'vl', 'h1',
        'vl', 'h1', 'vl', 'vl',
        'vl', 'l1', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    'p': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'l3', 'i1',
        'vl', 'l1', 'l2', 'h1',
        'vl', 'l4', 'hl', 'l2',
        'vl', 'vl', 'gd', 'gd',
        'l1', 'l2', 'gd', 'gd',
    ],
    'q': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'l3', 'vl',
        'vl', 'vl', 'vl', 'vl',
        'vl', 'vl', 'vl', 'i1',
        'vl', 'l1', 'l2', 'h1',
        'l1', 't4', 't2', 'l2',
    ],
    'r': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'l3', 'i1',
        'vl', 'l1', 'l2', 'h1',
        'vl', 'l4', 'hl', 't4',
        'vl', 't2', 'l3', 'vl',
        'l1', 'l2', 'l1', 'l2',
    ],
    's': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'hl', 'l2',
        'vl', 'l1', 'hl', 'l3',
        'l1', 'hl', 'l3', 'vl',
        'l4', 'hl', 'l2', 'vl',
        'l1', 'h4', 'i4', 'l2',
    ],
    't': [
        'l4', 'i2', 'h2', 'l3',
        'l1', 'l3', 'l4', 'l2',
        'gd', 'vl', 'vl', 'gd',
        'gd', 'vl', 'vl', 'gd',
        'gd', 'l1', 'l2', 'gd',
    ],
    'u': [
        'l4', 'l3', 'l4', 'l3',
        'vl', 'vl', 'i1', 'vl',
        'vl', 'vl', 'h1', 'vl',
        'vl', 'vl', 'vl', 'vl',
        'vl', 'l1', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    'v': [
        'l4', 'l3', 'l4', 'l3',
        'i1', 'vl', 'vl', 'vl',
        'h1', 'vl', 'vl', 'vl',
        'vl', 'l1', 'l2', 'vl',
        'l1', 'l3', 'l4', 'l2',
        'gd', 'l1', 'l2', 'gd',
    ],
    'w': [
        'l4', 'l3', 'l4', 'l3',
        'vl', 't2', 't4', 'vl',
        'vl', 'vl', 'vl', 'vl',
        'i1', 'i1', 'i1', 'vl',
        'h1', 'gd', 'gd', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    'x': [
        'l4', 'l3', 'l4', 'l3',
        'vl', 'l1', 'l2', 'vl',
        'l1', 'l3', 'l4', 'l2',
        'l4', 'l2', 'l1', 'l3',
        'i1', 'l4', 'l3', 'vl',
        'h2', 'l2', 'l1', 'l2',
    ],
    'y': [
        'l4', 'l3', 'l4', 'l3',
        'vl', 'vl', 'vl', 'i1',
        'vl', 'l1', 'l2', 'h1',
        'l1', 'l3', 'l4', 'l2',
        'gd', 'vl', 'vl', 'gd',
        'gd', 'l1', 'l2', 'gd',
    ],
    'z': [
        'l4', 'hl', 'hl', 'l3',
        'l1', 'hl', 'l3', 'vl',
        'gd', 'l4', 'l2', 'vl',
        'l4', 'l2', 'l4', 'l2',
        'vl', 'i4', 't3', 'l3',
        'l1', 'i2', 'h2', 'l2',
    ],
    '0': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'l3', 'i1',
        'vl', 'i1', 'vl', 'h1',
        'vl', 'h1', 'vl', 'vl',
        'vl', 'l1', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    '1': [
        'l4', 'hl', 'l3', 'gd',
        'l1', 'l3', 'i1', 'gd',
        'gd', 'vl', 'h1', 'gd',
        'gd', 'vl', 'vl', 'gd',
        'l4', 'l2', 'l1', 'l3',
        'l1', 'hl', 'hl', 'l2',
    ],
    '2': [
        'l4', 'hl', 'hl', 'l3',
        'l1', 'hl', 'l3', 'vl',
        'l4', 'hl', 'l2', 'vl',
        'vl', 'l4', 'hl', 'l2',
        'vl', 'l1', 'hl', 'l3',
        'l1', 'h4', 'i4', 'l2',
    ],
    '3': [
        'l4', 'hl', 'hl', 'l3',
        'l1', 'h4', 'i3', 'vl',
        'gd', 'l4', 'l2', 'vl',
        'gd', 'l1', 'l3', 'vl',
        'l4', 'hl', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    '4': [
        'l4', 'l3', 'l4', 'l3',
        'vl', 'vl', 'vl', 'i1',
        'vl', 'l1', 'l2', 'h1',
        'l1', 'hl', 'l3', 'vl',
        'gd', 'gd', 'vl', 'vl',
        'gd', 'gd', 'l1', 'l2',
    ],
    '5': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'hl', 'l2',
        'vl', 'l1', 'h4', 'i3',
        'l1', 'hl', 'l3', 'vl',
        'l4', 'hl', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    '6': [
        'l4', 'hl', 'hl', 'l3',
        'i1', 'l4', 'hl', 'l2',
        'h1', 'l1', 'hl', 'l3',
        'vl', 'l4', 'l3', 'vl',
        'vl', 'l1', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    '7': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'l3', 'i1',
        'l1', 'l2', 'vl', 'h1',
        'gd', 'gd', 'vl', 'vl',
        'gd', 'gd', 'vl', 'vl',
        'gd', 'gd', 'l1', 'l2',
    ],
    '8': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'l3', 'i1',
        'vl', 'l1', 'l2', 'h1',
        'vl', 'l4', 'l3', 'vl',
        'vl', 'l1', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    '9': [
        'l4', 'hl', 'hl', 'l3',
        'vl', 'l4', 'l3', 'i1',
        'vl', 'l1', 'l2', 'h1',
        'l1', 'hl', 'l3', 'vl',
        'l4', 'hl', 'l2', 'vl',
        'l1', 'hl', 'hl', 'l2',
    ],
    '_': [
        'gd', 'gd', 'gd', 'gd',
        'gd', 'gd', 'gd', 'gd',
        'gd', 'gd', 'gd', 'gd',
        'gd', 'gd', 'gd', 'gd',
        'gd', 'gd', 'gd', 'gd',
        'gd', 'gd', 'gd', 'gd',
    ]
}